import React, { Component } from "react";
import Head from 'next/head'

export default class ChangePass extends Component {
  constructor(props) {
    super(props);
    this.state = {
      oldPassword: "",
      password: "",
      confirmPassword:""
    };
    this.handleSubmit = this.handleSubmit.bind(this);
  }

//   handleSubmit(e) {
//     e.preventDefault();
//     const { oldPassword, password ,agreement} = this.state;
//     console.log(email, password);
//       (async () => {
//         let results = await fetch("https://63c69e4d7bc13e30efe4278c--searchinbackend.netlify.app/.netlify/functions/login-user"
//         , {
//     method: "POST",
//     body: JSON.stringify({
//         email,
//         password,
//     }),
//     }).then((response) => {
//     // *** Check for HTTP failure
//     console.log(response)
//     if (!response.ok) {
//       console.log(response.status)
//       if(response.status=="401" ||response.status=="500" ){
//         alert("wrong password or username");
//       }
//     throw new Error("HTTP status " + response.status);
//     }
//     // *** Read and parse the JSON          
    
//     return response.json();
//     })
//     .then((response) => {
//     // *** Use the object

//       alert("login successful");
//       console.log(email);
//       window.localStorage.setItem("token", response.data);
//       window.localStorage.setItem("email",email)
//       window.localStorage.setItem("loggedIn", true);
//       window.localStorage.setItem("stay", agreement);
//       window.location.href = "./";
    


//     })
//     .catch((error) => {   

    
//     /* ...*** handle/report error, since this code doesn't return the promise chain...*/
//     });}
//     )();


//   }
  render() {
    return (
      <>
      <Head>
      <title>Search In</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/icon.png" />
    </Head>
      <form onSubmit={this.handleSubmit} className="signin">
        <h3>Change Password</h3>

        <div className="mb-3">
          <input
            type="password"
            className="form-control"
            placeholder="Enter old password"
            onChange={(e) => this.setState({ oldPassword: e.target.value })}
          />
        </div>

        <div className="mb-3">
          <input
            type="password"
            className="form-control"
            placeholder="Enter password"
            onChange={(e) => this.setState({ password: e.target.value })}
          />
        </div>

        <div className="mb-3">
          <input
            type="password"
            className="form-control"
            placeholder="Confirm New Password"
            onChange={(e) => this.setState({ confirmPassword: e.target.value })}
          />
        </div>

        <div className="d-grid">
          <button type="submit" className="btn btn-primary">
            Submit
          </button>
        </div>

        <p className="forgot-password text-right">
          <a href="/">Go Back</a>
        </p>
      </form>
      </>
    );
  }
}