import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import App from './App.js'

const inter = Inter({ subsets: ['latin'] })
if (typeof window !== "undefined") {
  window.addEventListener("beforeunload", (ev) => 
{  
  if(window.localStorage.getItem("stay")){

  }else{
    localStorage.clear();
  }

    // ev.preventDefault();
    // return ev.returnValue = 'Are you sure you want to close?';
});
  // Client-side-only code
}


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
           {/* <a href='/SignIn'> Sign In</a>
           <a href='/SignUp'> Sign Up</a> */}
           <App/>
      </main>
    </>
  )
}
